### ISSUE TITLE
getaddrinfo ENOTFOUND from container manager proxy

### ISSUE THREAD

**Issue by Toshbrown** [me-box/core-network#3] opened 2018-03-12 12:58 UTC
I've been trying to track this down for a while, but it appears to be an issue with the core-network dns resolver. To repeat: 

./start-databox 
install driver-os-monitor 
install app-os-monitor 

Then go to the app-os-monitor ui (you will see the odd error in the cm logs *"ERROR: /app-os-monitor/ui/load.png?rand=0.7721667057062178 getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080"* but it mostly works) 

then: 
```
docker exec -it [container-manager id] sh
# nslookup app-os-monitor 10.0.0.3 (this should work)
# for i in `seq 1 10`; do echo "### $i ###"; nslookup app-os-monitor 10.0.0.3; done (this causes the falure)

from this point on dns resolution is completely broken 
```
If I increase the core-network dns log level I see a lot of `resolve app-os-monitor later...`  not sure if this is related but looks odd.

**Comment by sevenEng** [comment] 2018-03-12 13:02
Got this, will investigate!

**Comment by Toshbrown** [comment] 2018-03-19 12:44
@sevenEng did you get anywhere with this?

**Comment by sevenEng** [comment] 2018-03-19 18:51
Hi tosh, I've pushed something to a new `fix-dns` branch, hope that could solve this problem

when trying to replicate the problem, I found a lot of `resolve 248.0.0.10.in-addr.arpa later...` from the core-network's log, but not `resolve app-os-monitor later...`, I'm not sure if I solved the right problem, but a burst of `nslookup` indeed would crash the resolving

to work on this, I found that the cause was by this function: https://github.com/me-box/core-network/blob/master/lib/interfaces.ml#L108

which extracts a packet from the incoming stream of a particular interface, and if it's ok to process that, then pass the packet to `dispatch_fn`, after the processing, it tries to extract another packet, the function `dispatch_fn` is called in a synchronous fashion, which means if it takes a long time in this function, it will prevent the subsequent packets from being processed

in this DNS case, the reverse lookup will throw the resolver in a dead-end loop: https://github.com/me-box/core-network/blob/master/lib/dns_service.ml#L44, which will keep trying for 60 times before giving up, this will lead to the function `dispatch_fn` not returning for 60 seconds, and so the following resolving packets (and all the other kinds) can't be processed during this period

to solve this, I added something to detect a reverse lookup and just simply ignore them, this could make `dispatch_fn` returns promptly and a burst of DNS lookups could succeed then, but other solutions could be calling `dispatch_fn` in an async fashion

**Comment by Toshbrown** [comment] 2018-03-20 10:08
Cool, I will give it a test today. 

Thanks

**Comment by Toshbrown** [comment] 2018-03-20 11:03
This is an improvement 👍 

Now if a DNS request fails then future requests succeed. 

However, the DNS requests still seem to fail quite often: 

```
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] GET: /app-os-monitor/ui/mem.png => https://app-os-monitor:8080/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] GET: /app-os-monitor/ui/mem.png => https://app-os-monitor:8080/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] ERROR: /app-os-monitor/ui/mem.png getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] retry /app-os-monitor/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] ERROR: /app-os-monitor/ui/mem.png getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] retry /app-os-monitor/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] ERROR: /app-os-monitor/ui/mem.png getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] GET: /app-os-monitor/ui/mem.png => https://app-os-monitor:8080/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] GET: /app-os-monitor/ui/mem.png => https://app-os-monitor:8080/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] ERROR: /app-os-monitor/ui/mem.png getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] retry /app-os-monitor/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] ERROR: /app-os-monitor/ui/mem.png getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] ERROR: /app-os-monitor/ui/mem.png getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [Proxy] retry /app-os-monitor/ui/mem.png
databox_container-manager.1.85bnmz8tgxj3@linuxkit-025000000001    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/mem.png
```
 
Seems worse with larger requests mem.png fails more then arbiter/cat 

Also seems worse if requests run in parallel.

A quick test script to help you reproduce.

[databox-test-http.zip](https://github.com/me-box/core-network/files/1828989/databox-test-http.zip)

To use: 

start databox and install the os-monitor driver and app 

run it in the databox root dir.

**Comment by Toshbrown** [comment] 2018-04-04 16:45
@sevenEng I'm still having trouble with this, do you have any time to try and fix it? I'm 99% sure it a problem with the DNS resolver under load, but it could be a strange docker network issue.

**Comment by sevenEng** [comment] 2018-04-04 19:33
Yeah, of course, maybe it's worth caching some DNS responses? I'm thinking load testing the resolver first to see how it responds.

**Comment by Toshbrown** [comment] 2018-04-16 13:06
It looks like this is a problem that only occurs in docker for mac, all works well on Linux ;-(

**Comment by Toshbrown** [comment] 2018-04-16 13:20
Hum, I retract that last message, it occurs on Linux as well just less frequently:

```
databox_container-manager.1.w9ugbwrbiuka@tosh-VirtualBox    | [Proxy] GET: /app-os-monitor/ui/mem.png?rand=0.7026598766541237 => https://app-os-monitor:8080/ui/mem.png?rand=0.7026598766541237
databox_container-manager.1.w9ugbwrbiuka@tosh-VirtualBox    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/mem.png?rand=0.7026598766541237
databox_container-manager.1.w9ugbwrbiuka@tosh-VirtualBox    | [Proxy] GET: /app-os-monitor/ui/load.png?rand=0.1959975335717039 => https://app-os-monitor:8080/ui/load.png?rand=0.1959975335717039
databox_container-manager.1.w9ugbwrbiuka@tosh-VirtualBox    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/load.png?rand=0.1959975335717039
databox_container-manager.1.w9ugbwrbiuka@tosh-VirtualBox    | [Proxy] ERROR: /app-os-monitor/ui/mem.png?rand=0.7026598766541237 getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080
databox_container-manager.1.w9ugbwrbiuka@tosh-VirtualBox    | [Proxy] retry /app-os-monitor/ui/mem.png?rand=0.7026598766541237
databox_container-manager.1.w9ugbwrbiuka@tosh-VirtualBox    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/mem.png?rand=0.7026598766541237

```

**Closed as completed** 2018-04-16 14:19 UTC
